
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://D:\InteliJ\MSA
          uri: https://github.com/RedJunHee/MSA